import abc
from ..wire import Port, Pin


class ReadableMemory(metaclass=abc.ABCMeta):
    def read_enable(self) -> Pin: ...
    def addr(self) -> Port: ...
    def data(self) -> Port: ...


class ReadWriteMemory(ReadableMemory):
    def write_enable(self) -> Pin: ...
